### PR TITLE
fix route guard

### LINKED ISSUE #15: routeGuard always returning false
I am trying to write a navigation guard with vue-router that checks for authenticated status and do appropriate navigations.

I am following the examples in the repo and trying to implement something exactly like this: https://github.com/descope/vue-sdk/blob/main/example/router.ts#L40.

The problem is `routeGuard()` resolves with `false` always - irrespective of the auth status.

To reproduce: https://github.com/arvi-nagaraj/descope-vue 

Please help.

### PR DESCRIPTION
**Pull request by nirgur**
fixes #15

### CODE REVIEW

File: example/components/Login.vue [hunk 1]
```diff
@@ -6,7 +6,6 @@
 			<h1>You are authenticated</h1>
 		</div>
 		<Descope
-			v-else
```
Comment (asafshen) [inline example/components/Login.vue:9]: why removed?

File: src/Descope.vue [hunk 2]
```diff
@@ -58,13 +58,11 @@ const { projectId, baseUrl } = useOptions();
...
 
 const onSuccess = async (e: CustomEvent) => {
-	// Note: We need to emit AFTER the afterRequest hook has been called, but for
-	// an unknown reason, the emit is not called if we await the hook.
-	emit('success', e);
 	await sdk.httpClient.hooks?.afterRequest?.(
 		{} as RequestConfig,
 		new Response(JSON.stringify(e.detail))
 	);
+	emit('success', e);
```
Comment (asafshen) [inline src/Descope.vue:65]: I assume that the guard changes fixed the order issue (so the comment you removed is not relevant)

File: src/plugin.ts [hunk 3]
```diff
@@ -63,12 +63,22 @@ export default {
...
-			}
-			return !!unref(sessionToken);
-		};
+		routeGuardInternal.value = () =>
+			new Promise((resolve, reject) => {
+				if (!sessionToken.value && isFetchSessionWasNeverCalled.value) {
+					fetchSession().catch(reject);
+				}
+
+				// if the session is loading we want to wait for it to finish before resolving
```
Comment (asafshen) [inline src/plugin.ts:72]: useful comment  👍

File: src/plugin.ts [hunk 4]
```diff
@@ -63,12 +63,22 @@ export default {
...
-		routeGuardInternal.value = async () => {
-			if (!sessionToken.value && isFetchSessionWasNeverCalled.value) {
-				await fetchSession();
-			}
-			return !!unref(sessionToken);
-		};
+		routeGuardInternal.value = () =>
+			new Promise((resolve, reject) => {
+				if (!sessionToken.value && isFetchSessionWasNeverCalled.value) {
+					fetchSession().catch(reject);
```
Comment (asafshen) [inline src/plugin.ts:69]: I think that this was the issue root cause, 

there was an edge case that the session has fetched, but the `isSessionLoading` is not updated yet

File: src/plugin.ts [hunk 5]
```diff
@@ -63,12 +63,22 @@ export default {
...
+				// if the session is loading we want to wait for it to finish before resolving
+				if (isSessionLoading.value) {
+					watch(
+						() => isSessionLoading.value,
+						() => !isSessionLoading.value && resolve(!!unref(sessionToken))
+					);
+				} else {
+					resolve(!!unref(sessionToken));
+				}
+			});
```
Comment (asafshen) [inline src/plugin.ts:81]: I didn't test it, but we may be able to use [eager watcher](https://vuejs.org/guide/essentials/watchers.html#eager-watchers) to avoid this condition

```suggestion
				watch(
						() => isSessionLoading.value,
						() => !isSessionLoading.value && resolve(!!unref(sessionToken)),
						{ immediate: true }
					);
			});
```

**Review by asafshen — APPROVED** [review]
looks great 👍

File: src/plugin.ts (hunk 5 above)
Comment (nirgur) [reply src/plugin.ts]: Thanks!
I wasn't familiar with this option

File: example/components/Login.vue (hunk 1 above)
Comment (asafshen) [reply example/components/Login.vue:9]: but doesn't it means that the Descope will be rendered also if user is authenticated?

Comment (nirgur) [reply example/components/Login.vue:9]: It's on the login page, I think it's reasonable to render it
The alternative is that the success event will be dispatched before the session is updated 
which will lead us to the same problem as before
